name = "hono-template-bun"
main = "src/index.ts"
compatibility_date = "2025-02-03"

compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "development"

[env.staging.vars]
NODE_ENV = "staging"

[env.production.vars]
NODE_ENV = "production"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
# head_sampling_rate = 1

# [triggers]
# crons = ["30 6 * * 1", "30 6 * * 2"]
